"""
generate_statistics_notebook.py
--------------------------------
Run this once to create notebooks/4_statistics_analysis.ipynb
    python generate_statistics_notebook.py
"""

import json, os

def md(source_lines):
    return {"cell_type": "markdown", "metadata": {}, "source": source_lines}

def code(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines,
    }

cells = []

# ── Title ─────────────────────────────────────────────────────────────────────
cells.append(md([
    "# Nairobi Heat Vulnerability — Complete Statistical Analysis\n",
    "\n",
    "Compares **informal settlements** vs. the **rest of the city (formal)**,\n",
    "restricting all analyses to **inhabited pixels** (population > 0).\n",
    "\n",
    "Sections:\n",
    "1. Exposure — Land Surface Temperature (LST)\n",
    "2. Sensitivity — Population counts & Relative Wealth Index\n",
    "3. Adaptive Capacity — Access to services\n",
    "4. All-in-one summary table\n",
    "5. Summary dashboard figure\n",
]))

# ── 0. Imports & Paths ────────────────────────────────────────────────────────
cells.append(md(["## 0 — Imports & Paths\n",
                  "> Edit the paths below if your layout differs before running.\n"]))

cells.append(code([
    "import os, sys\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "import rasterio\n",
    "import rasterio.warp\n",
    "from rasterio.features import rasterize\n",
    "from rasterio.enums import Resampling\n",
    "from rasterio.warp import reproject\n",
    "from scipy.interpolate import griddata\n",
    "from scipy.stats import mannwhitneyu, ks_2samp\n",
    "import matplotlib.pyplot as plt\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "sys.path.append('../.')\n",
    "from src.common_helper import load_boundary, create_analysis_grid, PROJECT_ROOT, DATA_DIR, RESULTS_DIR\n",
    "from src.adaptive_capacity_helper import compute_proximity, compute_road_density\n",
    "from src.sensitivity_helper import resample_to_grid\n",
    "\n",
    "%matplotlib inline\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "# Output directory\n",
    "STATS_DIR = os.path.join(RESULTS_DIR, 'statistics')\n",
    "os.makedirs(STATS_DIR, exist_ok=True)\n",
    "\n",
    "# ── DATA PATHS  (edit if your layout differs) ────────────────────────────────\n",
    "INFORMAL_GJ  = os.path.join(RESULTS_DIR, 'exposure', 'informal_settlements_obia_2024.geojson')\n",
    "\n",
    "# LST GeoTIFFs  -- adjust path if needed\n",
    "LST = {\n",
    "    2020: os.path.join(PROJECT_ROOT, 'notebooks', 'results', 'lst_geotiffs', 'LST_2020.tif'),\n",
    "    2022: os.path.join(PROJECT_ROOT, 'notebooks', 'results', 'lst_geotiffs', 'LST_2022.tif'),\n",
    "    2024: os.path.join(PROJECT_ROOT, 'notebooks', 'results', 'lst_geotiffs', 'LST_2024.tif'),\n",
    "}\n",
    "\n",
    "# Population rasters (HDX WorldPop)\n",
    "POP_GENERAL  = os.path.join(DATA_DIR, 'sensitivity', 'nairobi_general_pop_2020.tif')\n",
    "POP_CHILDREN = os.path.join(DATA_DIR, 'sensitivity', 'nairobi_children_pop_2020.tif')\n",
    "POP_ELDERLY  = os.path.join(DATA_DIR, 'sensitivity', 'nairobi_elderly_pop_2020.tif')\n",
    "\n",
    "# Wealth index\n",
    "RWI_CSV = os.path.join(DATA_DIR, 'sensitivity', 'ken_relative_wealth_index.csv')\n",
    "\n",
    "# Adaptive capacity layers\n",
    "HEALTH_GJ  = os.path.join(DATA_DIR, 'adaptivity', 'Health_facilities_Nairobi.geojson')\n",
    "COOLING_GJ = os.path.join(DATA_DIR, 'adaptivity', 'cooling_centers_nairobi.geojson')\n",
    "WATER_GJ   = os.path.join(DATA_DIR, 'adaptivity', 'water_sources_nairobi.geojson')\n",
    "GREEN_GJ   = os.path.join(DATA_DIR, 'adaptivity', 'green_spaces_nairobi.geojson')\n",
    "ROADS_GJ   = os.path.join(DATA_DIR, 'adaptivity', 'major_roads.geojson')\n",
    "STREETS_GJ = os.path.join(DATA_DIR, 'adaptivity', 'street_edges.geojson')\n",
    "\n",
    "# Sanity check\n",
    "for label, p in [('Informal GeoJSON', INFORMAL_GJ),\n",
    "                  ('LST 2024',         LST[2024]),\n",
    "                  ('Population',       POP_GENERAL),\n",
    "                  ('RWI CSV',          RWI_CSV)]:\n",
    "    status = 'OK' if os.path.exists(p) else 'NOT FOUND'\n",
    "    print(f'  {status:10s}  {label}: {p}')\n",
]))

# ── 0b. Grid & masks ──────────────────────────────────────────────────────────
cells.append(md([
    "## 0b — Analysis grid & spatial masks\n",
    "\n",
    "- `informal_mask` — inhabited pixels inside informal settlement polygons\n",
    "- `formal_mask`   — inhabited pixels inside Nairobi but NOT informal\n",
    "- Population pixels with 0 people are excluded from both zones.\n",
]))

cells.append(code([
    "boundary = load_boundary()\n",
    "grid = create_analysis_grid(boundary, resolution_m=50)\n",
    "pixel_area_ha = (grid['resolution']**2) / 10_000\n",
    "print(f\"Grid: {grid['nrows']} x {grid['ncols']}  |  Nairobi cells: {grid['mask'].sum():,}\")\n",
]))

cells.append(code([
    "# Informal settlement mask from OBIA 2024 output\n",
    "informal_gdf = gpd.read_file(INFORMAL_GJ).to_crs(grid['crs'])\n",
    "informal_raster = rasterize(\n",
    "    [(geom, 1) for geom in informal_gdf.geometry if geom is not None],\n",
    "    out_shape=(grid['nrows'], grid['ncols']),\n",
    "    transform=grid['transform'],\n",
    "    fill=0, dtype='uint8',\n",
    ").astype(bool)\n",
    "\n",
    "# Population mask -- inhabited pixels only\n",
    "pop_raw = resample_to_grid(POP_GENERAL, grid, method=Resampling.sum)\n",
    "if pop_raw is not None:\n",
    "    pop_mask = (pop_raw > 0) & grid['mask']\n",
    "    print(f\"Inhabited cells: {pop_mask.sum():,}  ({pop_mask.sum()/grid['mask'].sum()*100:.1f}% of city)\")\n",
    "else:\n",
    "    print('WARNING: population raster not found -- using full city as mask')\n",
    "    pop_mask = grid['mask'].copy()\n",
    "\n",
    "# Final zone masks\n",
    "informal_mask = informal_raster & pop_mask\n",
    "formal_mask   = ~informal_raster & pop_mask\n",
    "\n",
    "print(f\"Informal (inhabited): {informal_mask.sum():,} cells  |  {informal_mask.sum()*pixel_area_ha:.0f} ha\")\n",
    "print(f\"Formal   (inhabited): {formal_mask.sum():,} cells  |  {formal_mask.sum()*pixel_area_ha:.0f} ha\")\n",
]))

# ── 1. LST ────────────────────────────────────────────────────────────────────
cells.append(md(["---\n", "## 1 — EXPOSURE: Land Surface Temperature\n",
                  "\n", "### 1a. LST statistics for 2024 (inhabited pixels only)\n"]))

cells.append(code([
    "def load_lst_on_grid(tif_path, grid):\n",
    "    \"\"\"Reproject a LST GeoTIFF onto the 50m analysis grid.\"\"\"\n",
    "    with rasterio.open(tif_path) as src:\n",
    "        dst = np.full((grid['nrows'], grid['ncols']), np.nan, dtype=np.float32)\n",
    "        reproject(\n",
    "            source=rasterio.band(src, 1),\n",
    "            destination=dst,\n",
    "            src_transform=src.transform, src_crs=src.crs,\n",
    "            dst_transform=grid['transform'], dst_crs=grid['crs'],\n",
    "            resampling=Resampling.bilinear,\n",
    "        )\n",
    "        dst[~grid['mask']] = np.nan\n",
    "    return dst\n",
    "\n",
    "lst_2024 = load_lst_on_grid(LST[2024], grid)\n",
    "\n",
    "def lst_stats_row(arr, mask, zone, year):\n",
    "    v = arr[mask]; v = v[np.isfinite(v)]\n",
    "    return {\n",
    "        'zone': zone, 'year': year, 'n_cells': len(v),\n",
    "        'mean_C': np.mean(v), 'median_C': np.median(v), 'std_C': np.std(v),\n",
    "        'min_C': np.min(v), 'max_C': np.max(v),\n",
    "        'p10_C': np.percentile(v, 10), 'p25_C': np.percentile(v, 25),\n",
    "        'p75_C': np.percentile(v, 75), 'p90_C': np.percentile(v, 90),\n",
    "        'p95_C': np.percentile(v, 95), 'p99_C': np.percentile(v, 99),\n",
    "    }\n",
    "\n",
    "rows_lst = [\n",
    "    lst_stats_row(lst_2024, informal_mask, 'Informal', 2024),\n",
    "    lst_stats_row(lst_2024, formal_mask,   'Formal (non-informal)', 2024),\n",
    "]\n",
    "lst_df = pd.DataFrame(rows_lst)\n",
    "lst_df.to_csv(os.path.join(STATS_DIR, 'lst_stats_2024.csv'), index=False)\n",
    "\n",
    "inf_vals = lst_2024[informal_mask]; inf_vals = inf_vals[np.isfinite(inf_vals)]\n",
    "for_vals = lst_2024[formal_mask];   for_vals = for_vals[np.isfinite(for_vals)]\n",
    "\n",
    "print(f\"Informal mean: {np.mean(inf_vals):.2f} C\")\n",
    "print(f\"Formal   mean: {np.mean(for_vals):.2f} C\")\n",
    "print(f\"Gap (Inf - For): {np.mean(inf_vals)-np.mean(for_vals):+.2f} C\")\n",
    "\n",
    "stat, pval = mannwhitneyu(inf_vals, for_vals, alternative='two-sided')\n",
    "print(f\"Mann-Whitney U: U={stat:.0f}, p={pval:.2e}\")\n",
    "ks_d, ks_p = ks_2samp(inf_vals, for_vals)\n",
    "print(f\"KS test: D={ks_d:.4f}, p={ks_p:.2e}\")\n",
    "\n",
    "display(lst_df)\n",
]))

cells.append(code([
    "fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n",
    "\n",
    "# Violin\n",
    "parts = axes[0].violinplot([inf_vals[::5], for_vals[::5]], positions=[1, 2],\n",
    "                             showmedians=True, showextrema=True)\n",
    "for pc, col in zip(parts['bodies'], ['#d73027', '#4393c3']):\n",
    "    pc.set_facecolor(col); pc.set_alpha(0.75)\n",
    "axes[0].set_xticks([1, 2])\n",
    "axes[0].set_xticklabels(['Informal', 'Formal'])\n",
    "axes[0].set_ylabel('LST (C)')\n",
    "axes[0].set_title('LST Distribution by Settlement Type (2024)', fontweight='bold')\n",
    "axes[0].grid(axis='y', linestyle='--', alpha=0.4)\n",
    "\n",
    "# Histogram\n",
    "axes[1].hist(inf_vals, bins=80, density=True, alpha=0.6, color='#d73027',\n",
    "             label=f'Informal  mean={np.mean(inf_vals):.1f} C')\n",
    "axes[1].hist(for_vals, bins=80, density=True, alpha=0.6, color='#4393c3',\n",
    "             label=f'Formal    mean={np.mean(for_vals):.1f} C')\n",
    "axes[1].axvline(np.mean(inf_vals), color='#d73027', linestyle='--', linewidth=1.8)\n",
    "axes[1].axvline(np.mean(for_vals), color='#4393c3', linestyle='--', linewidth=1.8)\n",
    "axes[1].set_xlabel('LST (C)'); axes[1].set_ylabel('Density')\n",
    "axes[1].set_title('LST Histogram (2024)', fontweight='bold')\n",
    "axes[1].legend(fontsize=9)\n",
    "axes[1].grid(axis='y', linestyle='--', alpha=0.4)\n",
    "\n",
    "plt.tight_layout()\n",
    "fig.savefig(os.path.join(STATS_DIR, 'lst_distribution_2024.png'), dpi=150)\n",
    "plt.show()\n",
]))

cells.append(md(["### 1b. Multi-year LST trend (2020 / 2022 / 2024)\n"]))

cells.append(code([
    "multi_rows = []\n",
    "for year in [2020, 2022, 2024]:\n",
    "    tif = LST[year]\n",
    "    if not os.path.exists(tif):\n",
    "        print(f'  LST_{year}.tif not found, skipping')\n",
    "        continue\n",
    "    arr = load_lst_on_grid(tif, grid)\n",
    "    for zone, mask in [('Informal', informal_mask), ('Formal (non-informal)', formal_mask)]:\n",
    "        multi_rows.append(lst_stats_row(arr, mask, zone, year))\n",
    "        v = arr[mask]; v = v[np.isfinite(v)]\n",
    "        print(f'  {year}  {zone}: mean={np.mean(v):.2f} C')\n",
    "\n",
    "lst_multi_df = pd.DataFrame(multi_rows)\n",
    "lst_multi_df.to_csv(os.path.join(STATS_DIR, 'lst_stats_all_years.csv'), index=False)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 5))\n",
    "for zone, col in [('Informal', '#d73027'), ('Formal (non-informal)', '#4393c3')]:\n",
    "    sub = lst_multi_df[lst_multi_df['zone'] == zone]\n",
    "    ax.plot(sub['year'], sub['mean_C'], 'o-', color=col, linewidth=2, markersize=7, label=zone)\n",
    "    ax.fill_between(sub['year'], sub['mean_C']-sub['std_C'], sub['mean_C']+sub['std_C'],\n",
    "                    color=col, alpha=0.15)\n",
    "ax.set_xlabel('Year'); ax.set_ylabel('Mean LST (C)')\n",
    "ax.set_title('LST Trend 2020-2024: Informal vs. Formal (inhabited pixels)', fontweight='bold')\n",
    "ax.legend(); ax.grid(linestyle='--', alpha=0.4)\n",
    "plt.tight_layout()\n",
    "fig.savefig(os.path.join(STATS_DIR, 'lst_trend_2020_2024.png'), dpi=150)\n",
    "plt.show()\n",
    "display(lst_multi_df)\n",
]))

# ── 2. SENSITIVITY ────────────────────────────────────────────────────────────
cells.append(md(["---\n", "## 2 — SENSITIVITY: Population & Wealth\n",
                  "\n", "### 2a. Population counts by settlement class\n"]))

cells.append(code([
    "def pop_zone_stats(tif_path, layer_name, masks_dict, grid):\n",
    "    arr = resample_to_grid(tif_path, grid, method=Resampling.sum)\n",
    "    if arr is None:\n",
    "        print(f'  {layer_name}: NOT FOUND'); return []\n",
    "    rows = []\n",
    "    for zone, mask in [('Informal', masks_dict['informal']), ('Formal (non-informal)', masks_dict['formal'])]:\n",
    "        v = arr[mask]; v = v[np.isfinite(v)]\n",
    "        total = float(np.nansum(v))\n",
    "        area  = float(np.sum(mask)) * pixel_area_ha\n",
    "        rows.append({'layer': layer_name, 'zone': zone,\n",
    "                     'total_count': total, 'area_ha': area,\n",
    "                     'pop_density_per_ha': total/area if area > 0 else np.nan})\n",
    "        print(f'  {layer_name} | {zone}: {total:,.0f} people  ({total/area:.1f}/ha)')\n",
    "    return rows\n",
    "\n",
    "masks_dict = {'informal': informal_mask, 'formal': formal_mask}\n",
    "pop_rows = []\n",
    "for path, name in [(POP_GENERAL,  'General population'),\n",
    "                    (POP_CHILDREN, 'Children <5'),\n",
    "                    (POP_ELDERLY,  'Elderly 65+')]:\n",
    "    pop_rows += pop_zone_stats(path, name, masks_dict, grid)\n",
    "\n",
    "pop_df = pd.DataFrame(pop_rows)\n",
    "pop_df.to_csv(os.path.join(STATS_DIR, 'sensitivity_population_stats.csv'), index=False)\n",
    "display(pop_df)\n",
]))

cells.append(md(["### 2b. Population-weighted LST (2024)\n",
    "> The temperature that the **average resident** actually experiences.\n"]))

cells.append(code([
    "if pop_raw is not None and os.path.exists(LST[2024]):\n",
    "    pw_rows = []\n",
    "    for zone, mask in [('Informal', informal_mask), ('Formal (non-informal)', formal_mask)]:\n",
    "        t = lst_2024[mask]; p = pop_raw[mask]\n",
    "        valid = np.isfinite(t) & np.isfinite(p) & (p > 0)\n",
    "        pw_mean = float(np.sum(t[valid]*p[valid]) / np.sum(p[valid])) if valid.sum() > 0 else np.nan\n",
    "        pw_rows.append({'zone': zone, 'year': 2024, 'pop_weighted_mean_lst_C': pw_mean})\n",
    "        print(f'  Pop-weighted LST {zone}: {pw_mean:.2f} C')\n",
    "    pw_df = pd.DataFrame(pw_rows)\n",
    "    pw_df.to_csv(os.path.join(STATS_DIR, 'pop_weighted_lst_2024.csv'), index=False)\n",
    "    display(pw_df)\n",
    "else:\n",
    "    print('Skipped: pop raster or LST 2024 not found')\n",
]))

cells.append(md(["### 2c. Relative Wealth Index (Sensitivity)\n",
    "> Negative = poorer than average, Positive = wealthier. Interpolated from RWI point data.\n"]))

cells.append(code([
    "boundary_gdf = load_boundary()\n",
    "rwi_df = pd.read_csv(RWI_CSV)\n",
    "rwi_gdf = gpd.GeoDataFrame(rwi_df,\n",
    "    geometry=gpd.points_from_xy(rwi_df.longitude, rwi_df.latitude), crs='EPSG:4326')\n",
    "rwi_nairobi = gpd.clip(rwi_gdf, boundary_gdf).to_crs(grid['crs'])\n",
    "\n",
    "minx, miny, maxx, maxy = grid['bounds']\n",
    "gx, gy = np.mgrid[minx:maxx:complex(0, grid['ncols']), maxy:miny:complex(0, grid['nrows'])]\n",
    "pts  = np.column_stack([rwi_nairobi.geometry.x, rwi_nairobi.geometry.y])\n",
    "vals = rwi_nairobi['rwi'].values\n",
    "grid_rwi = griddata(pts, vals, (gx, gy), method='linear').T\n",
    "grid_rwi[~grid['mask']] = np.nan\n",
    "\n",
    "rwi_rows = []\n",
    "for zone, mask in [('Informal', informal_mask), ('Formal (non-informal)', formal_mask)]:\n",
    "    v = grid_rwi[mask]; v = v[np.isfinite(v)]\n",
    "    rwi_rows.append({'zone': zone, 'n_points': len(v),\n",
    "                     'mean_rwi': np.mean(v), 'median_rwi': np.median(v),\n",
    "                     'std_rwi': np.std(v),\n",
    "                     'p10_rwi': np.percentile(v, 10), 'p90_rwi': np.percentile(v, 90),\n",
    "                     'pct_below_neg05': np.mean(v < -0.5)*100,\n",
    "                     'pct_above_pos05': np.mean(v > 0.5)*100})\n",
    "    print(f'  RWI {zone}: mean={np.mean(v):.3f}, pct very poor (< -0.5)={np.mean(v<-0.5)*100:.1f}%')\n",
    "\n",
    "rwi_summary = pd.DataFrame(rwi_rows)\n",
    "rwi_summary.to_csv(os.path.join(STATS_DIR, 'sensitivity_wealth_stats.csv'), index=False)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 5))\n",
    "for zone, col in [('Informal', '#d73027'), ('Formal (non-informal)', '#4393c3')]:\n",
    "    mask = informal_mask if zone == 'Informal' else formal_mask\n",
    "    v = grid_rwi[mask]; v = v[np.isfinite(v)]\n",
    "    ax.hist(v, bins=60, density=True, alpha=0.6, color=col, label=f'{zone} (mean={np.mean(v):.2f})')\n",
    "    ax.axvline(np.mean(v), color=col, linestyle='--', linewidth=1.8)\n",
    "ax.axvline(0, color='black', linewidth=0.8, linestyle=':', label='RWI=0 (average)')\n",
    "ax.set_xlabel('Relative Wealth Index'); ax.set_ylabel('Density')\n",
    "ax.set_title('Relative Wealth Index Distribution', fontweight='bold')\n",
    "ax.legend(fontsize=9); ax.grid(axis='y', linestyle='--', alpha=0.4)\n",
    "plt.tight_layout()\n",
    "fig.savefig(os.path.join(STATS_DIR, 'sensitivity_wealth_distribution.png'), dpi=150)\n",
    "plt.show()\n",
    "display(rwi_summary)\n",
]))

# ── 3. ADAPTIVE CAPACITY ─────────────────────────────────────────────────────
cells.append(md(["---\n", "## 3 — ADAPTIVE CAPACITY: Access to Services\n",
    "\n",
    "For each service we report **mean distance (m)** and **% of cells within 500m / 1 km / 2 km / 5 km**.\n"]))

cells.append(code([
    "def access_stats(gdf, layer_name, informal_mask, formal_mask, grid, max_dist_m, filter_fn=None):\n",
    "    if filter_fn: gdf = filter_fn(gdf)\n",
    "    print(f'  {layer_name}: {len(gdf)} features')\n",
    "    prox  = compute_proximity(gdf, grid)\n",
    "    dist  = (1 - prox) * max_dist_m\n",
    "    rows  = []\n",
    "    for zone, mask in [('Informal', informal_mask), ('Formal (non-informal)', formal_mask)]:\n",
    "        d = dist[mask]; d = d[np.isfinite(d)]\n",
    "        rows.append({'layer': layer_name, 'zone': zone,\n",
    "                     'mean_dist_m':   np.mean(d), 'median_dist_m': np.median(d),\n",
    "                     'std_dist_m':    np.std(d),\n",
    "                     'p25_dist_m':    np.percentile(d, 25),\n",
    "                     'p75_dist_m':    np.percentile(d, 75),\n",
    "                     'pct_within_500m':  np.mean(d <  500)*100,\n",
    "                     'pct_within_1km':   np.mean(d < 1000)*100,\n",
    "                     'pct_within_2km':   np.mean(d < 2000)*100,\n",
    "                     'pct_within_5km':   np.mean(d < 5000)*100})\n",
    "        print(f'    {zone}: mean={np.mean(d):.0f} m, within 1km={np.mean(d<1000)*100:.1f}%')\n",
    "    return rows\n",
    "\n",
    "ac_rows = []\n",
    "\n",
    "health_gdf = gpd.read_file(HEALTH_GJ)\n",
    "ac_rows += access_stats(health_gdf, 'Health facilities', informal_mask, formal_mask, grid,\n",
    "    max_dist_m=10000,\n",
    "    filter_fn=lambda g: g[g['Province']=='NAIROBI'] if 'Province' in g.columns else g)\n",
    "\n",
    "cooling_gdf = gpd.read_file(COOLING_GJ)\n",
    "ac_rows += access_stats(cooling_gdf, 'Cooling centres', informal_mask, formal_mask, grid, max_dist_m=5000)\n",
    "\n",
    "water_gdf = gpd.read_file(WATER_GJ)\n",
    "ac_rows += access_stats(water_gdf, 'Water sources', informal_mask, formal_mask, grid, max_dist_m=2000)\n",
    "\n",
    "green_gdf = gpd.read_file(GREEN_GJ)\n",
    "ac_rows += access_stats(green_gdf, 'Green spaces', informal_mask, formal_mask, grid, max_dist_m=5000)\n",
    "\n",
    "ac_df = pd.DataFrame(ac_rows)\n",
    "ac_df.to_csv(os.path.join(STATS_DIR, 'adaptive_capacity_stats.csv'), index=False)\n",
    "display(ac_df)\n",
]))

cells.append(md(["### 3b. Road density\n"]))
cells.append(code([
    "roads = gpd.read_file(ROADS_GJ)\n",
    "if os.path.exists(STREETS_GJ):\n",
    "    streets = gpd.read_file(STREETS_GJ)\n",
    "    roads = gpd.GeoDataFrame(\n",
    "        pd.concat([roads[['geometry']], streets[['geometry']]], ignore_index=True), crs=roads.crs)\n",
    "print(f'Total road segments: {len(roads):,}')\n",
    "road_dens = compute_road_density(roads, grid, bandwidth_m=500)\n",
    "rd_rows = []\n",
    "for zone, mask in [('Informal', informal_mask), ('Formal (non-informal)', formal_mask)]:\n",
    "    v = road_dens[mask]; v = v[np.isfinite(v)]\n",
    "    rd_rows.append({'zone': zone,\n",
    "                    'mean_road_density_score':   np.mean(v),\n",
    "                    'median_road_density_score': np.median(v),\n",
    "                    'std_road_density_score':    np.std(v)})\n",
    "    print(f'  Road density {zone}: mean score = {np.mean(v):.3f}')\n",
    "rd_df = pd.DataFrame(rd_rows)\n",
    "rd_df.to_csv(os.path.join(STATS_DIR, 'road_density_stats.csv'), index=False)\n",
    "display(rd_df)\n",
]))

cells.append(md(["### 3c. Distance bar chart\n"]))
cells.append(code([
    "layers_order = ac_df['layer'].unique()\n",
    "x     = np.arange(len(layers_order))\n",
    "width = 0.35\n",
    "fig, ax = plt.subplots(figsize=(12, 6))\n",
    "for i, (zone, col) in enumerate([('Informal', '#d73027'), ('Formal (non-informal)', '#4393c3')]):\n",
    "    sub   = ac_df[ac_df['zone'] == zone]\n",
    "    means = [sub[sub['layer']==l]['mean_dist_m'].values[0] for l in layers_order]\n",
    "    ax.bar(x + i*width, means, width, label=zone, color=col, alpha=0.82)\n",
    "ax.set_xticks(x + width/2)\n",
    "ax.set_xticklabels(layers_order, rotation=15, ha='right')\n",
    "ax.set_ylabel('Mean distance (m)')\n",
    "ax.set_title('Mean Distance to Services: Informal vs. Formal', fontweight='bold')\n",
    "ax.legend(); ax.grid(axis='y', linestyle='--', alpha=0.4)\n",
    "plt.tight_layout()\n",
    "fig.savefig(os.path.join(STATS_DIR, 'adaptive_capacity_distance_comparison.png'), dpi=150)\n",
    "plt.show()\n",
]))

# ── 4. SUMMARY TABLE ──────────────────────────────────────────────────────────
cells.append(md(["---\n", "## 4 — All-in-one Summary Table\n",
    "> One row per zone, all key indicators in a single wide table.\n"]))

cells.append(code([
    "summary_rows = []\n",
    "for zone, mask in [('Informal', informal_mask), ('Formal (non-informal)', formal_mask)]:\n",
    "    r = {'zone': zone, 'area_ha': float(np.sum(mask)) * pixel_area_ha}\n",
    "\n",
    "    # LST 2024\n",
    "    if 'lst_df' in dir():\n",
    "        sub = lst_df[lst_df['zone'] == zone]\n",
    "        if not sub.empty:\n",
    "            r.update({'lst_mean_C': sub['mean_C'].values[0],\n",
    "                      'lst_median_C': sub['median_C'].values[0],\n",
    "                      'lst_std_C': sub['std_C'].values[0],\n",
    "                      'lst_p95_C': sub['p95_C'].values[0]})\n",
    "\n",
    "    # Population\n",
    "    if 'pop_df' in dir():\n",
    "        for layer, key in [('General population','pop'), ('Children <5','children_u5'), ('Elderly 65+','elderly_65plus')]:\n",
    "            sub = pop_df[(pop_df['zone']==zone) & (pop_df['layer']==layer)]\n",
    "            if not sub.empty:\n",
    "                r[f'{key}_total'] = sub['total_count'].values[0]\n",
    "                r[f'{key}_dens_ha'] = sub['pop_density_per_ha'].values[0]\n",
    "\n",
    "    # Wealth\n",
    "    if 'rwi_summary' in dir():\n",
    "        sub = rwi_summary[rwi_summary['zone'] == zone]\n",
    "        if not sub.empty:\n",
    "            r['rwi_mean'] = sub['mean_rwi'].values[0]\n",
    "            r['rwi_pct_very_poor'] = sub['pct_below_neg05'].values[0]\n",
    "\n",
    "    # Adaptive capacity\n",
    "    if 'ac_df' in dir():\n",
    "        for layer in ac_df['layer'].unique():\n",
    "            sub = ac_df[(ac_df['zone']==zone) & (ac_df['layer']==layer)]\n",
    "            if not sub.empty:\n",
    "                key = layer.lower().replace(' ', '_')\n",
    "                r[f'{key}_mean_dist_m']   = sub['mean_dist_m'].values[0]\n",
    "                r[f'{key}_pct_within_1km'] = sub['pct_within_1km'].values[0]\n",
    "\n",
    "    summary_rows.append(r)\n",
    "\n",
    "summary_df = pd.DataFrame(summary_rows)\n",
    "summary_df.to_csv(os.path.join(STATS_DIR, 'all_in_one_summary.csv'), index=False)\n",
    "display(summary_df.T)\n",
]))

# ── 5. DASHBOARD ──────────────────────────────────────────────────────────────
cells.append(md(["---\n", "## 5 — Summary Dashboard Figure\n"]))

cells.append(code([
    "colors = {'Informal': '#d73027', 'Formal (non-informal)': '#4393c3'}\n",
    "zones  = list(summary_df['zone'])\n",
    "c_list = [colors[z] for z in zones]\n",
    "\n",
    "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n",
    "fig.suptitle('Nairobi Heat Vulnerability -- Key Statistics (2024)',\n",
    "             fontsize=16, fontweight='bold', y=0.98)\n",
    "\n",
    "def bar_panel(ax, title, values, zones, c_list, ylabel, fmt='{:.1f}'):\n",
    "    bars = ax.bar(zones, values, color=c_list, alpha=0.82, width=0.5)\n",
    "    for bar, v in zip(bars, values):\n",
    "        ax.text(bar.get_x()+bar.get_width()/2, v*1.01, fmt.format(v),\n",
    "                ha='center', va='bottom', fontsize=10, fontweight='bold')\n",
    "    ax.set_ylabel(ylabel); ax.set_title(title, fontweight='bold')\n",
    "    ax.grid(axis='y', linestyle='--', alpha=0.4)\n",
    "\n",
    "if 'lst_mean_C' in summary_df.columns:\n",
    "    bar_panel(axes[0,0], 'A -- Land Surface Temperature (2024)',\n",
    "              summary_df['lst_mean_C'].values, zones, c_list, 'Mean LST (C)', '{:.1f} C')\n",
    "\n",
    "if 'pop_dens_ha' in summary_df.columns:\n",
    "    bar_panel(axes[0,1], 'B -- Population Density',\n",
    "              summary_df['pop_dens_ha'].values, zones, c_list, 'People / ha', '{:.1f}')\n",
    "\n",
    "if 'rwi_mean' in summary_df.columns:\n",
    "    bar_panel(axes[1,0], 'C -- Relative Wealth Index (Sensitivity)',\n",
    "              summary_df['rwi_mean'].values, zones, c_list, 'Mean RWI', '{:.3f}')\n",
    "    axes[1,0].axhline(0, color='black', linewidth=0.8, linestyle='--')\n",
    "\n",
    "hcol = 'health_facilities_mean_dist_m'\n",
    "if hcol in summary_df.columns:\n",
    "    bar_panel(axes[1,1], 'D -- Distance to Nearest Health Facility',\n",
    "              summary_df[hcol].values, zones, c_list, 'Mean distance (m)', '{:.0f} m')\n",
    "\n",
    "plt.tight_layout()\n",
    "fig.savefig(os.path.join(STATS_DIR, 'summary_dashboard.png'), dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('All outputs saved to results/statistics/')\n",
]))

# ── Write notebook ────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out = os.path.join("notebooks", "4_statistics_analysis.ipynb")
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Notebook written to: {out}")
